# Use this only for production
# For development - see Makefile, "up" target
version: '3.9'
services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
    expose:
      - 80
    ports:
      - "80:80"
    networks:
      - vps-traefik
      - default

  api-gateway:
    build:
      context: api
      dockerfile: docker/nginx/Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/app
    depends_on:
      - db
      - api-php-fpm
    networks:
      - default

  api-php-fpm:
    image: natai/api-php-fpm:latest
    build:
      context: api
      dockerfile: docker/php/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app
    networks:
      - default

  frontend:
    image: natai/frontend:latest
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    env_file:
      - frontend/.env.prod.local
    restart: always
    networks:
      - default

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    networks:
      - default

volumes:
  db-data:

networks:
  default:
  vps-traefik:
    external: true