# Use this only for production
# For development - see Makefile, "up" target
version: '3.9'
services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - frontend
    expose:
      - 80
    networks:
      - vps-traefik
      - default
    labels:
      - "traefik.docker.network=vps-traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.natai.rule=Host(`natai.app`)"
      - "traefik.http.routers.natai.entrypoints=websecure"
      - "traefik.http.routers.natai.tls.certresolver=myresolver"
      # support for www.natai.app
      - "traefik.http.routers.www-natai.rule=Host(`www.natai.app`)"
      - "traefik.http.routers.www-natai.entrypoints=websecure"
      - "traefik.http.routers.www-natai.tls.certresolver=myresolver"

  api-gateway:
    build:
      context: api
      dockerfile: docker/nginx/Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/app
    depends_on:
      - db
      - api-php-fpm
    networks:
      - default

  api-php-fpm:
    image: natai/api-php-fpm:latest
    build:
      context: api
      dockerfile: docker/php/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./api:/app
    networks:
      - default

  api-queue:
    image: natai/api-php-fpm:latest
    restart: unless-stopped
    build:
      context: api
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./api:/app
    command: sh -c "bin/console messenger:consume async --limit=10"
    tty: true
    depends_on:
      - db
    networks:
      - default

  frontend:
    image: natai/frontend:latest
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    env_file:
      - frontend/.env.prod.local
    restart: always
    networks:
      - default

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - /home/deploy/natai/backup:/tmp/backup
    ports:
      - "35432:5432"
    networks:
      - default

volumes:
  db-data:

networks:
  default:
  vps-traefik:
    external: true