nelmio_api_doc:
    documentation:
        info:
            title: Natai Diary
            description: Diary Application for Anrdoid & WEB. Helps to track your daily activities and their effect on your mental health.
            version: 1.0.0
        components:
            securitySchemes:
                ApiToken:
                    type: apiKey
                    in: header
                    name: X-API-TOKEN
        security:
            - ApiToken: [ ]
#        components:
#            schemas:
#                Uuid:
#                    type: string
#                    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
#                    minLength: 36
#                    maxLength: 36
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
