nelmio_api_doc:
    documentation:
        info:
            title: Natai Diary
            description: Diary Application for Anrdoid & WEB. Helps to track your daily activities and their affect on your mental health.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
