version: '3.8'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: natai_db
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: natai_user
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: