common:
  type: attribute
  resource: ../src/Common/Controller/

attachment:
  type: attribute
  resource: ../src/Attachment/Controller/

auth:
  type: attribute
  resource: ../src/Auth/Controller/

diary:
  type: attribute
  resource: ../src/Diary/Controller/
